version: '3'

vars: #alphabetical list
  DUMMY: dummy

tasks:
####################################################################################################
# cluster tasks

  build:
    description: build the go module
    cmds:
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/varanus

  test:
    description: run tests
    cmds:
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go test -v ./...

  coverage-test:
    description: run tests
    vars:
      TEST_SCOPE: '{{if eq "" .CLI_ARGS}}./...{{else}}varanus/{{.CLI_ARGS}}{{end}}'
    cmds:
      - mkdir -p coverage
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go test -cover -coverprofile=coverage/coverage.out -v {{.TEST_SCOPE}}
      - go tool cover -html=coverage/coverage.out -o coverage/coverage.html

  clean:
    description: clean up output from test runs
    cmds:
      - rm -r internal/config/test_output || true
      - rm -r internal/app/test_output || true
      - rm -r internal/util/test_output || true


